export default [
  "images/Hard Surface/0-render002.jpg",
  "images/Hard Surface/wahhaj-asif-1.jpg",
  "images/Hard Surface/wahhaj-asif-2.jpg",
  "images/Hard Surface/wahhaj-asif-4.jpg",
  "images/Hard Surface/wahhaj-asif-capture.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot000 (1).jpg",
  "images/Hard Surface/wahhaj-asif-screenshot000-p.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot000.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot001 (1).jpg",
  "images/Hard Surface/wahhaj-asif-screenshot001.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot003 (1).jpg",
  "images/Hard Surface/wahhaj-asif-screenshot003.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot005.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot006.jpg",
  "images/Hard Surface/wahhaj-asif-screenshot012.jpg",
  "images/Hard Surface/wahhaj-sheikh-blenderdnoise500samplesuntitled2.jpg",
  "images/Hard Surface/wahhaj-sheikh-blenderdnoise500samplesuntitled4.jpg",
  "images/Hard Surface/wahhaj-sheikh-dcar-6.jpg",
  "images/Interior/chair2.jpg",
  "images/Interior/final.g1.jpg",
  "images/Interior/finaltrash.jpg",
  "images/Interior/room.jpg",
  "images/Interior/untitled.jpg",
  "images/Interior/untitled1.jpg"
];